name: github Package

on:
  push:
    branches:
      - main # or any other branch you want to trigger the publish from

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Specify the Node.js version
          registry-url: "https://npm.pkg.github.com" # Setup registry URL for GitHub Packages
          scope: "@sfiller23" # Replace with your GitHub username or organization

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      # Optional: Add and commit any additional changes
      - name: Add any uncommitted changes
        run: git add .

      - name: Commit any additional changes
        run: git commit -m "Include additional changes" || echo "No additional changes to commit."

      - name: Update package version and Publish to GitHub Packages
        run: |
          npm version patch -m "chore(release): bump version to %s"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # Push the commit created by npm version and any additional changes
      - name: Push changes
        run: git push
        env:
          GIT_AUTHOR_EMAIL: "action@github.com"
          GIT_AUTHOR_NAME: "GitHub Action"
          GIT_COMMITTER_EMAIL: "action@github.com"
          GIT_COMMITTER_NAME: "GitHub Action"
