name: publish npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          scope: "@cman430"
      - name: Install dependencies
        run: npm install

      - name: Change package scope
      run: |
        node -e "let pkg=require('./package.json'); pkg.name='@cman430/'+pkg.name.split('/').pop(); require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"

      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
